apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kub-app
  template:
    metadata:
      labels:
        app: kub-app
    spec:
      containers:
        - name: kub-app
          image: allayasheela/kub-app-pipeline:1.0.0-13
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
